# Generated by Django 2.2.1 on 2019-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
